//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlternateObserver
    {
        public int AlternateObserverID { get; set; }
        public Nullable<int> ChairID { get; set; }
        public Nullable<int> ObserverChairID { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public bool Active { get; set; }
    
        public virtual Chair Chair { get; set; }
        public virtual Chair Chair1 { get; set; }
    }
}
