//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttendanceRequirement
    {
        public int AttendanceRequirementsID { get; set; }
        public int ManagerDayRoundsRequired { get; set; }
        public int VPDayRoundsRequired { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public bool Active { get; set; }
    }
}
