//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChairSuperior
    {
        public int ChairHierarchyID { get; set; }
        public int ChairID { get; set; }
        public int SuperiorChairID { get; set; }
        public int Year { get; set; }
        public int Month { get; set; }
    
        public virtual Chair Chair { get; set; }
        public virtual Chair Chair1 { get; set; }
    }
}
