//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChairRoundingStatu
    {
        public int ChairRoundingStatusID { get; set; }
        public int ChairID { get; set; }
        public int NumberOfDirectRoundsComplete { get; set; }
        public int NumberOfAllStaffRoundsComplete { get; set; }
        public int NumberOfDirectRoundsRequired { get; set; }
        public int NumberOfAllStaffRoundsRequired { get; set; }
        public Nullable<double> AverageScoreOfDirectRounds { get; set; }
        public Nullable<double> AverageScoreOfSubmanagersRounds { get; set; }
        public Nullable<double> AverageScoreOfAllStaffRounds { get; set; }
        public int Year { get; set; }
        public int Month { get; set; }
    
        public virtual Chair Chair { get; set; }
    }
}
