//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Interaction
    {
        public Interaction()
        {
            this.InteractionStatus = new HashSet<InteractionStatu>();
            this.PracticeInteractions = new HashSet<PracticeInteraction>();
            this.RoundInteractions = new HashSet<RoundInteraction>();
        }
    
        public int InteractionID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Action { get; set; }
    
        public virtual ICollection<InteractionStatu> InteractionStatus { get; set; }
        public virtual ICollection<PracticeInteraction> PracticeInteractions { get; set; }
        public virtual ICollection<RoundInteraction> RoundInteractions { get; set; }
    }
}
