//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class InteractionStatu
    {
        public int TemplateID { get; set; }
        public int PracticeID { get; set; }
        public int InteractionID { get; set; }
        public bool Hidden { get; set; }
    
        public virtual Interaction Interaction { get; set; }
        public virtual Practice Practice { get; set; }
        public virtual Template Template { get; set; }
    }
}
