//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManagementRound
    {
        public ManagementRound()
        {
            this.ManagementRoundAttendances = new HashSet<ManagementRoundAttendance>();
        }
    
        public int ManagementRoundID { get; set; }
        public string Location { get; set; }
        public System.DateTime RoundDate { get; set; }
    
        public virtual ICollection<ManagementRoundAttendance> ManagementRoundAttendances { get; set; }
    }
}
