//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrganizationDeptCode
    {
        public OrganizationDeptCode()
        {
            this.RecoveryItemReplenishments = new HashSet<RecoveryItemReplenishment>();
            this.Users = new HashSet<User>();
        }
    
        public int OrganizationDeptCodeID { get; set; }
        public int Code { get; set; }
        public string DeptName { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual ICollection<RecoveryItemReplenishment> RecoveryItemReplenishments { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}
