//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrganizationStatu
    {
        public OrganizationStatu()
        {
            this.Users = new HashSet<User>();
        }
    
        public int OrganizationStatusId { get; set; }
        public string Status { get; set; }
    
        public virtual ICollection<User> Users { get; set; }
    }
}
