//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Practice
    {
        public Practice()
        {
            this.InteractionStatus = new HashSet<InteractionStatu>();
            this.PracticeInteractions = new HashSet<PracticeInteraction>();
            this.RoundInteractions = new HashSet<RoundInteraction>();
            this.TemplatePractices = new HashSet<TemplatePractice>();
        }
    
        public int PracticeID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public bool Library { get; set; }
        public int DepartmentID { get; set; }
        public int RoleID { get; set; }
        public Nullable<int> ParentID { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
        public string UserCreated { get; set; }
        public string UserModified { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual ICollection<InteractionStatu> InteractionStatus { get; set; }
        public virtual Role Role { get; set; }
        public virtual ICollection<PracticeInteraction> PracticeInteractions { get; set; }
        public virtual ICollection<RoundInteraction> RoundInteractions { get; set; }
        public virtual ICollection<TemplatePractice> TemplatePractices { get; set; }
    }
}
