//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recognition
    {
        public Recognition()
        {
            this.RecognitionRecipientMaps = new HashSet<RecognitionRecipientMap>();
        }
    
        public int RecognitionID { get; set; }
        public Nullable<int> RecognitionGiverUserID { get; set; }
        public int RecognitionGiverID { get; set; }
        public int RecognitionReasonID { get; set; }
        public bool IncludedThankYouCard { get; set; }
        public bool IncludedPersonalNote { get; set; }
        public bool IncludedRewardCard { get; set; }
        public string Comment { get; set; }
        public System.DateTime CreateDate { get; set; }
        public bool Approved { get; set; }
        public Nullable<int> ApproverUserID { get; set; }
        public Nullable<System.DateTime> ApprovalDate { get; set; }
        public Nullable<int> RoundID { get; set; }
        public Nullable<int> RewardGiverUserID { get; set; }
    
        public virtual RecognitionGiver RecognitionGiver { get; set; }
        public virtual RecognitionReason RecognitionReason { get; set; }
        public virtual Round Round { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual User User2 { get; set; }
        public virtual ICollection<RecognitionRecipientMap> RecognitionRecipientMaps { get; set; }
    }
}
