//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecoveryItemReplenishment
    {
        public int RecoveryItemReplenishmentID { get; set; }
        public int RecoveryItemID { get; set; }
        public int OrganizationDeptCodeID { get; set; }
        public System.DateTime DateOfLastNotification { get; set; }
    
        public virtual OrganizationDeptCode OrganizationDeptCode { get; set; }
        public virtual RecoveryItem RecoveryItem { get; set; }
    }
}
