//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecoveryItem
    {
        public RecoveryItem()
        {
            this.RecoveryItemReplenishments = new HashSet<RecoveryItemReplenishment>();
            this.ServiceRecoveryDetails = new HashSet<ServiceRecoveryDetail>();
        }
    
        public int RecoveryItemID { get; set; }
        public string Name { get; set; }
        public int ReplenishmentThreshold { get; set; }
        public bool Active { get; set; }
    
        public virtual ICollection<RecoveryItemReplenishment> RecoveryItemReplenishments { get; set; }
        public virtual ICollection<ServiceRecoveryDetail> ServiceRecoveryDetails { get; set; }
    }
}
