//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Round
    {
        public Round()
        {
            this.ChairRoundingScores = new HashSet<ChairRoundingScore>();
            this.Recognitions = new HashSet<Recognition>();
            this.RoundInteractions = new HashSet<RoundInteraction>();
            this.RoundObservers = new HashSet<RoundObserver>();
        }
    
        public int RoundID { get; set; }
        public int TemplateID { get; set; }
        public int UserID { get; set; }
        public int ChairID { get; set; }
        public string Comment { get; set; }
        public System.DateTime RoundDate { get; set; }
        public System.DateTime DateCreate { get; set; }
        public int ObserverID { get; set; }
        public int ObserverChairID { get; set; }
    
        public virtual Chair Chair { get; set; }
        public virtual Chair Chair1 { get; set; }
        public virtual ICollection<ChairRoundingScore> ChairRoundingScores { get; set; }
        public virtual ICollection<Recognition> Recognitions { get; set; }
        public virtual Template Template { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual ICollection<RoundInteraction> RoundInteractions { get; set; }
        public virtual ICollection<RoundObserver> RoundObservers { get; set; }
    }
}
