//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceRecovery
    {
        public ServiceRecovery()
        {
            this.ServiceRecoveryDetails = new HashSet<ServiceRecoveryDetail>();
        }
    
        public int ServiceRecoveryID { get; set; }
        public int RecordingUserID { get; set; }
        public string Comment { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<ServiceRecoveryDetail> ServiceRecoveryDetails { get; set; }
    }
}
