//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Template
    {
        public Template()
        {
            this.InteractionStatus = new HashSet<InteractionStatu>();
            this.Rounds = new HashSet<Round>();
            this.TemplatePractices = new HashSet<TemplatePractice>();
        }
    
        public int TemplateID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Status { get; set; }
        public int DepartmentID { get; set; }
        public Nullable<int> ParentID { get; set; }
        public string UserCreated { get; set; }
        public string UserModified { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
        public string Comment { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual ICollection<InteractionStatu> InteractionStatus { get; set; }
        public virtual ICollection<Round> Rounds { get; set; }
        public virtual ICollection<TemplatePractice> TemplatePractices { get; set; }
    }
}
